version: #{build}
image:
  - Visual Studio 2017
environment:
  # Define versions of Node.js
  matrix:
    - node_js: '' # latest node
    - node_js: 9
    - node_js: 8
    - node_js: 7
    - node_js: 6.14 # minimum
clone_depth: 5
matrix:
  fast_finish: true
  allow_failures:
    - node_js: ''
# Define platforms
platform:
  - x64
cache:
# - node_modules
  - '%LOCALAPPDATA%\Yarn'
init:
  # Install the platform version of Node.js
  - ps: Install-Product node $env:node_js $env:platform
  # Output useful info for debugging
  - node --version
  - npm --version
  - yarn --version
  - ps: $PSVersionTable.PSVersion
install:
  # Install the latest version of Yarn
  - ps: >-
      Write-Host "Installing Yarn!"

      (New-Object Net.WebClient).DownloadFile("https://yarnpkg.com/latest.msi", "$env:temp\yarn.msi")

      cmd /c start /wait msiexec.exe /i $env:temp\yarn.msi /quiet /qn /norestart
  # Install modules
  - yarn install
before_test: 
  - npm i codeclimate-test-reporter
test_script:
  # run test script 
  - npm t
after_test: 
  # send coverage report 
  - ps: Get-Content .\coverage\lcov.info | .\node_modules\.bin\codeclimate-test-reporter
build: off
